### ISSUE TITLE
./gradlew gem failed if version has "-SNAPSHOT" keyword

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/gradle-embulk-plugins#80]
## Environment

* OS: macOS 10.14.6
* Java: 1.8.0_192
* gradle: 6.2
* gradle-embulk-plugins: 0.3.0

* [commit](https://github.com/hiroyuki-sato/embulk-parser-jsonpath/commit/270696b43a8e8d4499a2f307361cfc0eea488fbb)
* [branch](https://github.com/hiroyuki-sato/embulk-parser-jsonpath/commits/topic/use-gradle-embulk-plugins)

## Expect behavior.

`./gradlew gem --stacktrace` generate gem.

## Actual behavior

I got the following error and build gem failed.

[Complete error](https://gist.github.com/hiroyuki-sato/11518013a0fdab9df5b6f0b1dc05fc57#file-embulk-txt)

### Note

It seems that this error relates to the version string in `build.gradle`

NG

```
version = "0.3.2-SNAPSHOT"
```

OK

```
version = "0.3.2
```

If the version string is `version = "0.3.2-SNAPSHOT`, It create `embulk-parser-jsonpath-0.3.2.pre.SNAPSHOT-java.gem` in `./build/gemContents/` directory.
It has `.pre.` string in a filename.

```
./gradlew gem --stacktrace

...

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gem'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
```

**Comment by dmikurube** [comment]
I believe this would be fixed in #83 -- to be releases in v0.4.0 soon. Note that Gradle 6+ is needed.

**Comment by dmikurube** [comment]
@hiroyuki-sato v0.4.0 is out. Please try it with Gradle 6+.

**Comment by hiroyuki-sato** [comment]
@dmikurube Thanks! It seems worked well.

```
version = "0.3.2-SNAPSHOT"
```


```
./gradlew gem
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :gem
Executing: `java org.jruby.Main -rjars/setup -S gem build embulk-parser-jsonpath.gemspec`
    with working directory at: /Users/user/OpenProjects/embulk/embulk-parser-jsonpath/build/gemContents
    with classpath: [ /Users/user/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.7.0/308120bca38f617e7b275af8ce0cbd9f0be66218/jruby-complete-9.2.7.0.jar ]
  Successfully built RubyGem
  Name: embulk-parser-jsonpath
  Version: 0.3.2.snapshot
  File: embulk-parser-jsonpath-0.3.2.snapshot-java.gem
Executing `gem build` finished successfully.
Moved build/gemContents/embulk-parser-jsonpath-0.3.2.snapshot-java.gem to build/gems/embulk-parser-jsonpath-0.3.2.snapshot-java.gem.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 13s
3 actionable tasks: 1 executed, 2 up-to-date
```
